### ISSUE TITLE
How to use with Elastic Cloud Kibana?

### ISSUE THREAD

**Issue by wrathagom** [devdjdjdj/kibana-presenter#10]
Specifically to handle auth for a dashboard? or does the dashboard have to be public in some way?

**Comment by devdjdjdj** [comment]
The application is internally embedding the dashboards. If the dashboards are available to be embedded then kibana-presenter should work with them.

In case of cloud auth, you'll have to login once. I would suggest creating a user with read only permissions for the dashboards (something like kibana_dashboard_only_user. I know it's deprecated, so another way would be using [Kibana Priviledges](https://www.elastic.co/guide/en/kibana/7.7/kibana-privileges.html#kibana-feature-privileges) ). I haven't tried testing the limits of kibana's auto session expire, but hopefully that isn't a problem as dashboard partially refresh when you go from one tab to another.

For the next release of kibana-presenter, I am experimenting with [Kibana APIs](https://www.elastic.co/guide/en/kibana/7.7/api.html) According to Elastic, they are currently experimental)

Let me know if you have any more questions or concerns.
